#!/usr/bin/env bash
# Assemble a DKMS tarball from drivers/md/ + dkms/
# Pipeline:
#   1. Copy manifest sources from drivers/md/ to a flat tarball directory
#   2. Copy dkms/compat/ into the tarball
#   3. Apply kernel-API compat patches (dkms/patches/*.patch) in glob-sorted order
#   4. Run rename pass (dkms/rename.sed) to translate md_* -> ms_*
#   5. Rename source filenames (md.c -> ms.c, raid1.c -> raid1_ms.c, etc.)
#   6. Render templates with version substituted
#   7. Tar the result
# Usage: dkms/scripts/build-tarball.sh <version>
set -euo pipefail

VER="${1:?usage: $0 <version>}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT="$REPO_ROOT/build/meshstor-ms-$VER"

cd "$REPO_ROOT"
rm -rf "$OUT"
mkdir -p "$OUT"

# 1. Copy kernel sources per manifest (one file per line, supports globs)
while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    [[ "$entry" =~ ^# ]] && continue
    cp drivers/md/$entry "$OUT/"
done < dkms/manifest.txt

# 2. Copy compat layer
cp -r dkms/compat "$OUT/"

# 2b. Stub feature_flags.h. The REAL feature detection happens at
#     module-build time (dkms/Makefile.in's `feature_flags` target),
#     because DKMS rebuilds against the customer's running kernel —
#     whose APIs may differ from whatever kernel produced this tarball.
#     Keeping a stub here prevents `compat.h`'s `#include "feature_flags.h"`
#     from ever failing if somebody runs `make` without going through
#     the wrapper Makefile.
{
    echo "/* SPDX-License-Identifier: GPL-2.0-or-later */"
    echo "/* Stub - real feature flags generated by dkms/Makefile.in at"
    echo " * module-build time against the running kernel's headers. */"
    echo "#ifndef MESHSTOR_MS_FEATURE_FLAGS_H"
    echo "#define MESHSTOR_MS_FEATURE_FLAGS_H"
    echo "#endif"
} > "$OUT/compat/feature_flags.h"

# Patches that need pre-rename feature flags (e.g., 0001 references
# HAVE_GETGEO_GENDISK) are still applied — but they reference the flag
# whose define is supplied at build time by the wrapper Makefile, so
# the source compiles correctly under either present-or-absent path.

# 3. Apply pre-rename compat patches (kernel-API gaps). See dkms/patches/README.md.
shopt -s nullglob
for p in dkms/patches/*.patch; do
    echo "Applying $(basename "$p")"
    patch -p1 -d "$OUT" --no-backup-if-mismatch < "$p"
done
shopt -u nullglob

# 4. Run the parallel-subsystem rename pass on every .c and .h.
# Auto-generate keep-list rules for kernel UAPI MD_* / md_* identifiers
# (extracted from <linux/raid/md_p.h>, <linux/raid/md_u.h>, <linux/major.h>)
# and prepend them to dkms/rename.sed for this run.
KDIR="${KDIR:-/lib/modules/$(uname -r)/build}"
RENAME_SED=$(mktemp)
{
    echo "# === Auto-generated keep rules (kernel UAPI from $KDIR) ==="
    grep -hoE "\bMD_[A-Z_][A-Z_0-9]*\b" \
        "$KDIR/include/uapi/linux/raid/md_p.h" \
        "$KDIR/include/uapi/linux/raid/md_u.h" \
        "$KDIR/include/uapi/linux/major.h" 2>/dev/null \
        | sort -u \
        | awk '{ printf "s/\\b%s\\b/__KEEP_%s/g\n", $0, $0 }'
    grep -hoE "\bmd_[a-z_][a-z_0-9]*\b" \
        "$KDIR/include/uapi/linux/raid/md_p.h" \
        "$KDIR/include/uapi/linux/raid/md_u.h" 2>/dev/null \
        | sort -u \
        | awk '{ printf "s/\\b%s\\b/__KEEP_%s/g\n", $0, $0 }'
    cat dkms/rename.sed
} > "$RENAME_SED"

echo "Applying rename pass (md_* -> ms_*)"
shopt -s nullglob
for f in "$OUT"/*.c "$OUT"/*.h; do
    sed -i -f "$RENAME_SED" "$f"
done
shopt -u nullglob
rm -f "$RENAME_SED"

# 5. Rename source filenames so the wrapper Makefile finds ms_*.c / raid*_ms.c.
cd "$OUT"
for f in md.c md.h md-bitmap.c md-bitmap.h md-cluster.h md-llbitmap.c md-autodetect.c; do
    [ -e "$f" ] && mv "$f" "${f/md/ms}"
done
[ -e raid1.c ]    && mv raid1.c    raid1_ms.c
[ -e raid1.h ]    && mv raid1.h    raid1_ms.h
[ -e raid10.c ]   && mv raid10.c   raid10_ms.c
[ -e raid10.h ]   && mv raid10.h   raid10_ms.h
[ -e raid1-10.c ] && mv raid1-10.c raid1-10_ms.c

# 5b. Inject the extern declaration for ms_major into ms.h so other TUs
#     (ms-autodetect.c, raid1_ms.c, etc.) can reference the variable defined
#     in ms.c. Insert after the include guard.
if [ -e ms.h ] && ! grep -q "extern int ms_major" ms.h; then
    sed -i '/^#ifndef _MD_MD_H\|^#ifndef _MS_MS_H\|^#ifndef.*MS_H/{
        a\
\
/* meshstor-ms parallel subsystem: dynamic block-device major (set in ms_init) */\
extern int ms_major;\
extern int msp_major;
        :a
    }' ms.h
fi
cd "$REPO_ROOT"

# 6. Render templates with version substituted
sed "s/@VERSION@/$VER/g" dkms/dkms.conf.in > "$OUT/dkms.conf"
sed "s/@VERSION@/$VER/g" dkms/Makefile.in  > "$OUT/Makefile"

# License
cp dkms/COPYING "$OUT/"

# 7. Tarball
cd "$REPO_ROOT/build"
tar czf "meshstor-ms-$VER.dkms.tar.gz" "meshstor-ms-$VER/"

echo "Built: $REPO_ROOT/build/meshstor-ms-$VER.dkms.tar.gz"
