#!/usr/bin/env bash
# Assemble a DKMS tarball from drivers/md/ + dkms/
# Pipeline:
#   1. Copy manifest sources from drivers/md/ to a flat tarball directory
#   2. Copy dkms/compat/ into the tarball
#   3. Apply kernel-API compat patches (dkms/patches/*.patch) in glob-sorted order
#   4. Run rename pass (dkms/rename.sed) to translate md_* -> ms_*
#   5. Rename source filenames (md.c -> ms.c, raid1.c -> raid1_ms.c, etc.)
#   6. Render templates with version substituted
#   7. Tar the result
# Usage: dkms/scripts/build-tarball.sh <version>
set -euo pipefail

VER="${1:?usage: $0 <version>}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT="$REPO_ROOT/build/meshstor-ms-$VER"

cd "$REPO_ROOT"
rm -rf "$OUT"
mkdir -p "$OUT"

# 1. Copy kernel sources per manifest (one file per line, supports globs)
while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    [[ "$entry" =~ ^# ]] && continue
    cp drivers/md/$entry "$OUT/"
done < dkms/manifest.txt

# 2. Copy compat layer
cp -r dkms/compat "$OUT/"

# 2b. Feature-detect: scan target kernel headers and generate feature_flags.h
#     BEFORE patches and rename pass, so both can reference HAVE_<SYMBOL>.
KDIR_FOR_DETECT="${KDIR:-/lib/modules/$(uname -r)/build}"
{
    echo "/* SPDX-License-Identifier: GPL-2.0-or-later */"
    echo "/* Auto-generated by dkms/scripts/build-tarball.sh on $(date -Idate) */"
    echo "/* Target kernel headers: $KDIR_FOR_DETECT */"
    echo "#ifndef MESHSTOR_MS_FEATURE_FLAGS_H"
    echo "#define MESHSTOR_MS_FEATURE_FLAGS_H"
    echo ""
    # Detection helpers: each tries multiple headers and emits #define HAVE_X
    # if the symbol is found. Always returns 0 (set -e + return 1 on miss
    # would silently abort the script).
    detect_sym() {
        local sym="$1" found=0
        shift
        for hdr in "$@"; do
            if [ -f "$KDIR_FOR_DETECT/include/$hdr" ] && \
               grep -qE "\b$sym\b" "$KDIR_FOR_DETECT/include/$hdr"; then
                found=1
                break
            fi
        done
        if [ "$found" = "1" ]; then
            echo "#define HAVE_${sym^^} 1"
        fi
        return 0
    }
    detect_sym bio_submit_split_bioset       linux/bio.h linux/blkdev.h
    detect_sym bio_init_inline                linux/bio.h
    detect_sym bdev_rot                       linux/blkdev.h
    detect_sym bdev_count_inflight            linux/blkdev.h linux/part_stat.h
    detect_sym bdev_write_zeroes_unmap_sectors linux/blkdev.h
    detect_sym timer_container_of             linux/timer.h
    detect_sym kzalloc_obj                    linux/slab.h
    detect_sym kmalloc_obj                    linux/slab.h
    detect_sym kzalloc_objs                   linux/slab.h
    detect_sym kmalloc_objs                   linux/slab.h
    detect_sym kvzalloc_objs                  linux/slab.h
    detect_sym kmalloc_flex                   linux/slab.h
    detect_sym kzalloc_flex                   linux/slab.h
    if [ -f "$KDIR_FOR_DETECT/include/linux/workqueue.h" ] && \
       grep -qE "^\s*#\s*define\s+WQ_PERCPU\b" "$KDIR_FOR_DETECT/include/linux/workqueue.h"; then
        echo "#define HAVE_WQ_PERCPU 1"
    fi
    # Signature detection: block_device_operations.getgeo callback type.
    if [ -f "$KDIR_FOR_DETECT/include/linux/blkdev.h" ] && \
       grep -qE "int \(\*getgeo\)\(struct gendisk" "$KDIR_FOR_DETECT/include/linux/blkdev.h"; then
        echo "#define HAVE_GETGEO_GENDISK 1"
    fi
    # badblocks_check sector_t-typed args 3 and 5 (r10+ has sector_t; r9/5.14 has int).
    # Declaration spans multiple lines — use awk to flatten.
    if [ -f "$KDIR_FOR_DETECT/include/linux/badblocks.h" ] && \
       awk 'BEGIN{RS=";"} /badblocks_check.*sector_t \*bad_sectors/' \
           "$KDIR_FOR_DETECT/include/linux/badblocks.h" | grep -q .; then
        echo "#define HAVE_BADBLOCKS_CHECK_SECTOR_T_OUTPUTS 1"
    fi
    # alloc_page_buffers 2-arg form (r10+); 3-arg with bool retry on r9.
    if [ -f "$KDIR_FOR_DETECT/include/linux/buffer_head.h" ] && \
       grep -qE "alloc_page_buffers\(struct page \*page, unsigned long size\)" "$KDIR_FOR_DETECT/include/linux/buffer_head.h"; then
        echo "#define HAVE_ALLOC_PAGE_BUFFERS_2ARG 1"
    fi
    echo ""
    echo "#endif /* MESHSTOR_MS_FEATURE_FLAGS_H */"
} > "$OUT/compat/feature_flags.h"

# 3. Apply pre-rename compat patches (kernel-API gaps). See dkms/patches/README.md.
shopt -s nullglob
for p in dkms/patches/*.patch; do
    echo "Applying $(basename "$p")"
    patch -p1 -d "$OUT" --no-backup-if-mismatch < "$p"
done
shopt -u nullglob

# 4. Run the parallel-subsystem rename pass on every .c and .h.
# Auto-generate keep-list rules for kernel UAPI MD_* / md_* identifiers
# (extracted from <linux/raid/md_p.h>, <linux/raid/md_u.h>, <linux/major.h>)
# and prepend them to dkms/rename.sed for this run.
KDIR="${KDIR:-/lib/modules/$(uname -r)/build}"
RENAME_SED=$(mktemp)
{
    echo "# === Auto-generated keep rules (kernel UAPI from $KDIR) ==="
    grep -hoE "\bMD_[A-Z_][A-Z_0-9]*\b" \
        "$KDIR/include/uapi/linux/raid/md_p.h" \
        "$KDIR/include/uapi/linux/raid/md_u.h" \
        "$KDIR/include/uapi/linux/major.h" 2>/dev/null \
        | sort -u \
        | awk '{ printf "s/\\b%s\\b/__KEEP_%s/g\n", $0, $0 }'
    grep -hoE "\bmd_[a-z_][a-z_0-9]*\b" \
        "$KDIR/include/uapi/linux/raid/md_p.h" \
        "$KDIR/include/uapi/linux/raid/md_u.h" 2>/dev/null \
        | sort -u \
        | awk '{ printf "s/\\b%s\\b/__KEEP_%s/g\n", $0, $0 }'
    cat dkms/rename.sed
} > "$RENAME_SED"

echo "Applying rename pass (md_* -> ms_*)"
shopt -s nullglob
for f in "$OUT"/*.c "$OUT"/*.h; do
    sed -i -f "$RENAME_SED" "$f"
done
shopt -u nullglob
rm -f "$RENAME_SED"

# 5. Rename source filenames so the wrapper Makefile finds ms_*.c / raid*_ms.c.
cd "$OUT"
for f in md.c md.h md-bitmap.c md-bitmap.h md-cluster.h md-llbitmap.c md-autodetect.c; do
    [ -e "$f" ] && mv "$f" "${f/md/ms}"
done
[ -e raid1.c ]    && mv raid1.c    raid1_ms.c
[ -e raid1.h ]    && mv raid1.h    raid1_ms.h
[ -e raid10.c ]   && mv raid10.c   raid10_ms.c
[ -e raid10.h ]   && mv raid10.h   raid10_ms.h
[ -e raid1-10.c ] && mv raid1-10.c raid1-10_ms.c

# 5b. Inject the extern declaration for ms_major into ms.h so other TUs
#     (ms-autodetect.c, raid1_ms.c, etc.) can reference the variable defined
#     in ms.c. Insert after the include guard.
if [ -e ms.h ] && ! grep -q "extern int ms_major" ms.h; then
    sed -i '/^#ifndef _MD_MD_H\|^#ifndef _MS_MS_H\|^#ifndef.*MS_H/{
        a\
\
/* meshstor-ms parallel subsystem: dynamic block-device major (set in ms_init) */\
extern int ms_major;\
extern int msp_major;
        :a
    }' ms.h
fi
cd "$REPO_ROOT"

# 6. Render templates with version substituted
sed "s/@VERSION@/$VER/g" dkms/dkms.conf.in > "$OUT/dkms.conf"
sed "s/@VERSION@/$VER/g" dkms/Makefile.in  > "$OUT/Makefile"

# License
cp dkms/COPYING "$OUT/"

# 7. Tarball
cd "$REPO_ROOT/build"
tar czf "meshstor-ms-$VER.dkms.tar.gz" "meshstor-ms-$VER/"

echo "Built: $REPO_ROOT/build/meshstor-ms-$VER.dkms.tar.gz"
