/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * meshstor-md compatibility shims for kernels older than upstream HEAD.
 *
 * Each shim is gated on a HAVE_<SYMBOL> feature flag (see feature_flags.h),
 * NOT on LINUX_VERSION_CODE: RHEL and Ubuntu HWE backport recent APIs into
 * older kernels, so a version check both misses backported capabilities and
 * mis-detects them. A few shims additionally test RHEL_RELEASE_CODE where a
 * capability can't be expressed by a single symbol probe.
 *
 * Add a new shim by:
 *   1. Identifying the symbol or macro the build wants but the kernel lacks.
 *   2. Adding its detection to dkms/Makefile.in's feature_flags recipe
 *      (the symbol:header list, or a custom signature probe).
 *   3. Adding the shim below, gated on #ifndef HAVE_<SYMBOL>.
 *   4. Documenting in the comment block above the shim.
 */
#ifndef MESHSTOR_MD_COMPAT_H
#define MESHSTOR_MD_COMPAT_H

/*
 * All kernel headers needed by any shim below are pulled in here at the top.
 * compat.h is force-included via the Makefile's -include flag, so it is the
 * first thing every translation unit sees. Shims that use kernel types
 * (struct block_device, struct bio, etc.) need the relevant headers
 * already in scope when the static inline is parsed; otherwise gcc emits
 * "struct foo declared inside parameter list" warnings and the type ends up
 * incompatible with the kernel's definition seen later.
 */
#include <linux/version.h>
#include <linux/types.h>
#include <linux/slab.h>
#include <linux/bio.h>

/*
 * feature_flags.h is auto-generated by dkms/Makefile.in's feature_flags
 * recipe at module-build time, from a scan of the target (running) kernel's
 * headers. (bin/build-tarball only ships a no-op stub.) It defines
 * HAVE_<SYMBOL> macros for symbols the kernel already provides natively, so
 * our compat shims below can be #ifndef-gated correctly across distros and
 * backports.
 */
#include "feature_flags.h"
#include <linux/blkdev.h>
#include <linux/blk_types.h>
#include <linux/workqueue.h>

/* RHEL release detection */
#ifndef RHEL_RELEASE_CODE
#define RHEL_RELEASE_CODE 0
#endif
#ifndef RHEL_RELEASE_VERSION
#define RHEL_RELEASE_VERSION(a,b) 0
#endif

/* Shims go here, sorted by introduction-version of the upstream symbol. */

/*
 * kzalloc_obj / kzalloc_objs / kmalloc_obj / kmalloc_objs
 *
 * Upstream introduces these as part of the treewide commit 7ea7c43e
 * "treewide: Replace kmalloc with kmalloc_obj for non-scalar types".
 * Each name has a 1-arg form (uses default GFP_KERNEL) and a 2-arg form
 * with explicit GFP. Same for *_objs (3-arg form takes type, count, gfp).
 *
 * Backport via existing kzalloc/kmalloc/kcalloc primitives. sizeof(x)
 * accepts both a dereferenced pointer (e.g. kzalloc_obj(*ptr)) and a
 * type name (e.g. kzalloc_obj(struct foo)).
 *
 * Variadic macro overload-by-arg-count technique is the standard way
 * to provide multiple arities for the same name in C99+.
 */

#define _MD_COMPAT_GET_3RD(_1, _2, _3, NAME, ...) NAME
#define _MD_COMPAT_GET_2ND(_1, _2, NAME, ...) NAME

/* kzalloc_obj(x) -> GFP_KERNEL ; kzalloc_obj(x, gfp) -> explicit */
#if !defined(HAVE_KZALLOC_OBJ) && !defined(kzalloc_obj)
#define _kzalloc_obj_1(x)      kzalloc(sizeof(x), GFP_KERNEL)
#define _kzalloc_obj_2(x, gfp) kzalloc(sizeof(x), (gfp))
#define kzalloc_obj(...) \
    _MD_COMPAT_GET_2ND(__VA_ARGS__, _kzalloc_obj_2, _kzalloc_obj_1)(__VA_ARGS__)
#endif

#if !defined(HAVE_KMALLOC_OBJ) && !defined(kmalloc_obj)
#define _kmalloc_obj_1(x)      kmalloc(sizeof(x), GFP_KERNEL)
#define _kmalloc_obj_2(x, gfp) kmalloc(sizeof(x), (gfp))
#define kmalloc_obj(...) \
    _MD_COMPAT_GET_2ND(__VA_ARGS__, _kmalloc_obj_2, _kmalloc_obj_1)(__VA_ARGS__)
#endif

/* kzalloc_objs(type, n) / kzalloc_objs(type, n, gfp) */
#if !defined(HAVE_KZALLOC_OBJS) && !defined(kzalloc_objs)
#define _kzalloc_objs_2(type, n)      kcalloc((n), sizeof(type), GFP_KERNEL)
#define _kzalloc_objs_3(type, n, gfp) kcalloc((n), sizeof(type), (gfp))
#define kzalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kzalloc_objs_3, _kzalloc_objs_2)(__VA_ARGS__)
#endif

#if !defined(HAVE_KMALLOC_OBJS) && !defined(kmalloc_objs)
#define _kmalloc_objs_2(type, n)      kmalloc_array((n), sizeof(type), GFP_KERNEL)
#define _kmalloc_objs_3(type, n, gfp) kmalloc_array((n), sizeof(type), (gfp))
#define kmalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kmalloc_objs_3, _kmalloc_objs_2)(__VA_ARGS__)
#endif

/* kvzalloc_objs / kvmalloc_objs — vmalloc-fallback variants. */
#if !defined(HAVE_KVZALLOC_OBJS) && !defined(kvzalloc_objs)
#define _kvzalloc_objs_2(type, n)      kvzalloc(array_size((n), sizeof(type)), GFP_KERNEL)
#define _kvzalloc_objs_3(type, n, gfp) kvzalloc(array_size((n), sizeof(type)), (gfp))
#define kvzalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kvzalloc_objs_3, _kvzalloc_objs_2)(__VA_ARGS__)
#endif

#if !defined(kvmalloc_objs)
#define _kvmalloc_objs_2(type, n)      kvmalloc(array_size((n), sizeof(type)), GFP_KERNEL)
#define _kvmalloc_objs_3(type, n, gfp) kvmalloc(array_size((n), sizeof(type)), (gfp))
#define kvmalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kvmalloc_objs_3, _kvmalloc_objs_2)(__VA_ARGS__)
#endif

/*
 * kmalloc_flex(*ptr, member, count, gfp)
 *
 * Allocates a struct with a trailing flexible-array member. First arg is the
 * dereferenced pointer (so typeof(*ptr) yields the struct type), second is
 * the flex-member name, third is the count, fourth is GFP.
 *
 * Backport via struct_size + kmalloc. struct_size handles the size math
 * (including the flexible-array member) safely against multiplication overflow.
 */
#if !defined(HAVE_KMALLOC_FLEX) && !defined(kmalloc_flex)
#define kmalloc_flex(deref_obj, member, count, gfp) \
    ({ \
        typeof(deref_obj) *_p = NULL; \
        kmalloc(struct_size(_p, member, (count)), (gfp)); \
    })
#endif

#if !defined(HAVE_KZALLOC_FLEX) && !defined(kzalloc_flex)
#define kzalloc_flex(deref_obj, member, count, gfp) \
    ({ \
        typeof(deref_obj) *_p = NULL; \
        kzalloc(struct_size(_p, member, (count)), (gfp)); \
    })
#endif

/*
 * bdev_rot()
 *
 * Upstream renames/adds bdev_rot(b) as the positive form of "is rotational".
 * 6.12 has the negative bdev_nonrot(b). Trivial inverse.
 */
#ifndef HAVE_BDEV_ROT
static inline bool bdev_rot(struct block_device *bdev)
{
    return !bdev_nonrot(bdev);
}
#endif

/*
 * bdev_count_inflight()
 *
 * Upstream adds this helper to count inflight bios on a block_device.
 * 6.12 lacks it. The single user (md.c::is_mddev_idle) compares against
 * the previous count to decide if the device is "idle." Returning 0 makes
 * the device always report idle, which biases the heuristic toward "yes"
 * but is not a correctness issue — sync_speed display may be slightly off.
 *
 * TODO: revisit with a real backport via part_stat_read once we identify
 * the exact field semantics.
 */
#ifndef HAVE_BDEV_COUNT_INFLIGHT
static inline unsigned int bdev_count_inflight(struct block_device *bdev)
{
    (void)bdev;
    return 0;
}
#endif

/*
 * WQ_PERCPU
 *
 * New workqueue flag in upstream. On older kernels, defining it as 0 is
 * a safe no-op — alloc_workqueue ignores unknown bits in the flags arg.
 */
#if !defined(HAVE_WQ_PERCPU) && !defined(WQ_PERCPU)
#define WQ_PERCPU 0
#endif

/*
 * bdev_write_zeroes_unmap_sectors
 *
 * Upstream adds this distinct API to query write-zeroes-with-unmap
 * sector limit, separate from plain bdev_write_zeroes_sectors. Older
 * kernels don't have the distinction.
 *
 * Safe fallback: return 0, which causes md-llbitmap to skip the
 * write-zeroes-unmap optimization and fall back to the standard sync path.
 */
#ifndef HAVE_BDEV_WRITE_ZEROES_UNMAP_SECTORS
static inline unsigned int bdev_write_zeroes_unmap_sectors(struct block_device *bdev)
{
    (void)bdev;
    return 0;
}
#endif

/*
 * timer_container_of(var, callback_timer, fieldname)
 *
 * Upstream renames from_timer() → timer_container_of() (same expansion).
 * Provide the new name as an alias on older kernels.
 */
#if !defined(HAVE_TIMER_CONTAINER_OF) && !defined(timer_container_of)
#define timer_container_of from_timer
#endif

/*
 * bio_init_inline(bio, bdev, nr_vecs, opf)
 *
 * Upstream introduces this variant of bio_init that uses bio->bi_inline_vecs
 * as the bvec array. On older kernels we don't have it; bio_init takes the
 * bvec array explicitly. Pass the inline vecs ourselves.
 */
#ifndef HAVE_BIO_INIT_INLINE
static inline void bio_init_inline(struct bio *bio, struct block_device *bdev,
                                    unsigned short nr_vecs, blk_opf_t opf)
{
    bio_init(bio, bdev, bio->bi_inline_vecs, nr_vecs, opf);
}
#endif

/*
 * bio_submit_split_bioset()
 *
 * Upstream introduces this helper around v6.18. Semantics: split off
 * `sectors` from the front of `bio` using bioset `bs`, chain remainder,
 * submit the split via submit_bio_noacct, and return the original bio
 * (now representing the remainder) so the caller can continue.
 *
 * Backport via existing bio_split + bio_chain + submit_bio_noacct,
 * all of which exist in 6.12.
 */
#ifndef HAVE_BIO_SUBMIT_SPLIT_BIOSET
static inline struct bio *bio_submit_split_bioset(struct bio *bio,
                                                   unsigned int sectors,
                                                   struct bio_set *bs)
{
    struct bio *split;

    split = bio_split(bio, sectors, GFP_NOIO, bs);
    if (IS_ERR(split))
        return NULL;
    bio_chain(split, bio);
    submit_bio_noacct(split);
    return bio;
}
#endif

/*
 * badblocks_check signature change (5.14 → 6.12)
 *
 * Old (RHEL 9 / 5.14): args 3 and 5 are `int sectors` and `int *bad_sectors`.
 * New (6.12+):         args 3 and 5 are `sector_t sectors` and `sector_t *bad_sectors`.
 * Our integrated source uses the new form. Wrap on older kernels.
 */
#ifndef HAVE_BADBLOCKS_CHECK_SECTOR_T_OUTPUTS
#include <linux/badblocks.h>
static inline int ms_badblocks_check_compat(struct badblocks *bb, sector_t s,
                                              sector_t sectors,
                                              sector_t *first_bad,
                                              sector_t *bad_sectors)
{
    int ifirst = 0, isectors = 0;
    int rc;
    rc = badblocks_check(bb, s, (int)sectors, (sector_t *)&ifirst, &isectors);
    if (first_bad) *first_bad = ifirst;
    if (bad_sectors) *bad_sectors = isectors;
    return rc;
}
#define badblocks_check ms_badblocks_check_compat
#endif

/*
 * alloc_page_buffers argument count (5.14 → 6.12)
 *
 * Old: alloc_page_buffers(page, size, bool retry)
 * New: alloc_page_buffers(page, size)
 * Our integrated source calls the 2-arg form.
 */
#ifndef HAVE_ALLOC_PAGE_BUFFERS_2ARG
#include <linux/buffer_head.h>
#define alloc_page_buffers(page, size) alloc_page_buffers((page), (size), false)
#endif

/*
 * UAPI constants removed/added between Ubuntu 24.04 GA (6.8) and 6.12.
 */
#include <linux/raid/md_u.h>
#ifndef LEVEL_LINEAR
#define LEVEL_LINEAR (-1)
#endif

/*
 * REQ_ATOMIC bio flag (atomic-writes infrastructure, ~6.10+).
 * On older kernels atomic-write paths are not exercised; defining as 0
 * makes the bit-OR / test_bit calls no-op without breaking the build.
 */
#include <linux/blk_types.h>
#ifndef REQ_ATOMIC
#define REQ_ATOMIC ((__force blk_opf_t)0)
#endif

/*
 * BLK_STS_INVAL (added in 6.10, commit 7ba150834b04).
 *
 * Used by raid1_should_handle_error to skip retry/badblocks when the bio
 * was rejected for being invalid for the underlying device. On older
 * kernels this status is never emitted, so any unused sentinel value
 * works — pick one well above the highest defined BLK_STS_* in 6.8.
 */
#ifndef BLK_STS_INVAL
#define BLK_STS_INVAL  ((__force blk_status_t)0xFE)
#endif

/*
 * queue_limits transactional update API (added in 6.9, commits c490f226a0eaf
 * and 631d4efb80fb).
 *
 * Newer kernels mutate queue limits via a copy-edit-commit cycle:
 *   lim = queue_limits_start_update(q);
 *   ...mutate lim...
 *   queue_limits_commit_update(q, &lim);   (or _cancel_update on abort)
 * Older kernels just assign q->limits directly.
 *
 * The shims below implement the same contract on 6.8 by copying limits
 * into and out of the queue. There is no transactional rollback, so
 * _cancel_update is a no-op — callers using cancel_update accept that
 * partial mutations to the local `lim` are simply discarded by going
 * out of scope.
 */
#ifndef HAVE_QUEUE_LIMITS_START_UPDATE
static inline struct queue_limits queue_limits_start_update(struct request_queue *q)
{
    return q->limits;
}
#endif

#ifndef HAVE_QUEUE_LIMITS_COMMIT_UPDATE
static inline int queue_limits_commit_update(struct request_queue *q,
                                              struct queue_limits *lim)
{
    q->limits = *lim;
    return 0;
}
#endif

#ifndef HAVE_QUEUE_LIMITS_CANCEL_UPDATE
static inline void queue_limits_cancel_update(struct request_queue *q)
{
    (void)q;
}
#endif

/*
 * queue_limits_set (added in 6.9). One-shot apply of a queue_limits to a
 * queue. On 6.8, also set the queue flags that 6.11+ encodes in
 * lim->features (WRITE_CACHE | FUA | IO_STAT | NOWAIT) — patch 0005
 * elides those bitmap assignments on pre-6.11 kernels, so this shim is
 * the single place where the "features" of an md stacking device get
 * applied to the queue.
 */
#ifndef HAVE_QUEUE_LIMITS_SET
static inline int queue_limits_set(struct request_queue *q,
                                    struct queue_limits *lim)
{
    q->limits = *lim;
    blk_queue_write_cache(q, true, true);
    blk_queue_flag_set(QUEUE_FLAG_IO_STAT, q);
    blk_queue_flag_set(QUEUE_FLAG_NOWAIT, q);
    return 0;
}
#endif

/*
 * queue_limits_stack_bdev (added in 6.9). Stack a block_device's limits
 * onto a queue_limits target. 6.8 has the equivalent at the queue_limits
 * level via blk_stack_limits — same semantics, just no disk-name in
 * mismatch warnings.
 */
#ifndef HAVE_QUEUE_LIMITS_STACK_BDEV
static inline void queue_limits_stack_bdev(struct queue_limits *t,
                                            struct block_device *bdev,
                                            sector_t offset,
                                            const char *name)
{
    blk_stack_limits(t, &bdev_get_queue(bdev)->limits, offset);
    (void)name;
}
#endif

/*
 * queue_limits_stack_integrity_bdev (added in 6.10). Validates and stacks
 * a bdev's blk_integrity profile onto a queue_limits target. Returns true
 * if profiles are compatible, false otherwise.
 *
 * 6.8 has no queue_limits-level integrity stacking — integrity is set up
 * via blk_integrity_register on the gendisk after creation. Returning
 * true here means the caller's "incompatible integrity" rejection path
 * is never taken on 6.8; runtime mismatches still surface elsewhere.
 * This is a deliberate compat trade-off: degraded validation, never a
 * hard build break.
 */
#ifndef HAVE_QUEUE_LIMITS_STACK_INTEGRITY_BDEV
static inline bool queue_limits_stack_integrity_bdev(struct queue_limits *t,
                                                      struct block_device *bdev)
{
    (void)t; (void)bdev;
    return true;
}
#endif

/*
 * bdev_file_open_by_dev / file_bdev (added in 6.9, commit 8acbac46d27dd).
 *
 * The transition replaced struct bdev_handle * with struct file * as the
 * holder type. On 6.8 we reinterpret-cast bdev_handle as struct file *:
 * the pointer is opaque to md.c (only file_bdev() extracts the bdev,
 * and release goes through ms_bdev_file_release() — see below). It is
 * never dereferenced as a real struct file.
 *
 * This works because struct file is forward-declared but its layout is
 * never used on the bdev_file path. Keep this contract intact: any new
 * use of rdev->bdev_file must go through these shims.
 */
#ifndef HAVE_BDEV_FILE_OPEN_BY_DEV
static inline struct file *bdev_file_open_by_dev(dev_t dev, blk_mode_t mode,
                                                   void *holder,
                                                   const struct blk_holder_ops *hops)
{
    return (struct file *)bdev_open_by_dev(dev, mode, holder, hops);
}

static inline struct block_device *file_bdev(struct file *bdev_file)
{
    return ((struct bdev_handle *)bdev_file)->bdev;
}
#endif

/*
 * ms_bdev_file_release(bdev_file)
 *
 * fput() can't be retargeted because md.c also fputs real bitmap files
 * in the same translation unit. Patch 0006 rewrites the two
 * fput(rdev->bdev_file) call sites to use this helper, which dispatches
 * to fput() on 6.9+ and bdev_release() on 6.8.
 */
#ifdef HAVE_BDEV_FILE_OPEN_BY_DEV
static inline void ms_bdev_file_release(struct file *bdev_file)
{
    fput(bdev_file);
}
#else
static inline void ms_bdev_file_release(struct file *bdev_file)
{
    bdev_release((struct bdev_handle *)bdev_file);
}
#endif

/*
 * blk_alloc_disk(lim, node) — 2-arg form added in 6.9 (commit 74fa8f9c5530).
 * On 6.8 the macro is `blk_alloc_disk(node)`. Redefine to accept the
 * (lim, node) signature, dropping `lim` — the limits get applied by a
 * subsequent queue_limits_set() (real on 6.9+ or shim on 6.8).
 *
 * Must come AFTER <linux/blkdev.h> so the original macro is in scope to
 * be #undef'd. The expansion mirrors the 6.8 blkdev.h definition (uses
 * __blk_alloc_disk + a static lock_class_key).
 */
#ifndef HAVE_BLK_ALLOC_DISK_LIM
#ifdef blk_alloc_disk
#undef blk_alloc_disk
#endif
#define blk_alloc_disk(lim, node_id)                                    \
({                                                                       \
    static struct lock_class_key __key;                                  \
    (void)(lim);                                                         \
    __blk_alloc_disk(node_id, &__key);                                   \
})
#endif

#endif /* MESHSTOR_MD_COMPAT_H */
