/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * meshstor-md compatibility shims for kernels older than upstream HEAD.
 *
 * Each shim is gated on a HAVE_<SYMBOL> feature flag (see feature_flags.h),
 * NOT on LINUX_VERSION_CODE: RHEL and Ubuntu HWE backport recent APIs into
 * older kernels, so a version check both misses backported capabilities and
 * mis-detects them. A few shims additionally test RHEL_RELEASE_CODE where a
 * capability can't be expressed by a single symbol probe.
 *
 * Add a new shim by:
 *   1. Identifying the symbol or macro the build wants but the kernel lacks.
 *   2. Adding its detection to dkms/Makefile.in's feature_flags recipe
 *      (the symbol:header list, or a custom signature probe).
 *   3. Adding the shim below, gated on #ifndef HAVE_<SYMBOL>.
 *   4. Documenting in the comment block above the shim.
 */
#ifndef MESHSTOR_MD_COMPAT_H
#define MESHSTOR_MD_COMPAT_H

/*
 * All kernel headers needed by any shim below are pulled in here at the top.
 * compat.h is force-included via the Makefile's -include flag, so it is the
 * first thing every translation unit sees. Shims that use kernel types
 * (struct block_device, struct bio, etc.) need the relevant headers
 * already in scope when the static inline is parsed; otherwise gcc emits
 * "struct foo declared inside parameter list" warnings and the type ends up
 * incompatible with the kernel's definition seen later.
 */
#include <linux/version.h>
#include <linux/types.h>
#include <linux/slab.h>
#include <linux/bio.h>

/*
 * feature_flags.h is auto-generated by dkms/Makefile.in's feature_flags
 * recipe at module-build time, from a scan of the target (running) kernel's
 * headers. (bin/build-tarball only ships a no-op stub.) It defines
 * HAVE_<SYMBOL> macros for symbols the kernel already provides natively, so
 * our compat shims below can be #ifndef-gated correctly across distros and
 * backports.
 */
#include "feature_flags.h"
#include <linux/blkdev.h>
#include <linux/blk_types.h>
#include <linux/workqueue.h>

/* RHEL release detection */
#ifndef RHEL_RELEASE_CODE
#define RHEL_RELEASE_CODE 0
#endif
#ifndef RHEL_RELEASE_VERSION
#define RHEL_RELEASE_VERSION(a,b) 0
#endif

/* Shims go here, sorted by introduction-version of the upstream symbol. */

/*
 * kzalloc_obj / kzalloc_objs / kmalloc_obj / kmalloc_objs
 *
 * Upstream introduces these as part of the treewide commit 7ea7c43e
 * "treewide: Replace kmalloc with kmalloc_obj for non-scalar types".
 * Each name has a 1-arg form (uses default GFP_KERNEL) and a 2-arg form
 * with explicit GFP. Same for *_objs (3-arg form takes type, count, gfp).
 *
 * Backport via existing kzalloc/kmalloc/kcalloc primitives. sizeof(x)
 * accepts both a dereferenced pointer (e.g. kzalloc_obj(*ptr)) and a
 * type name (e.g. kzalloc_obj(struct foo)).
 *
 * Variadic macro overload-by-arg-count technique is the standard way
 * to provide multiple arities for the same name in C99+.
 */

#define _MD_COMPAT_GET_3RD(_1, _2, _3, NAME, ...) NAME
#define _MD_COMPAT_GET_2ND(_1, _2, NAME, ...) NAME

/* kzalloc_obj(x) -> GFP_KERNEL ; kzalloc_obj(x, gfp) -> explicit */
#if !defined(HAVE_KZALLOC_OBJ) && !defined(kzalloc_obj)
#define _kzalloc_obj_1(x)      kzalloc(sizeof(x), GFP_KERNEL)
#define _kzalloc_obj_2(x, gfp) kzalloc(sizeof(x), (gfp))
#define kzalloc_obj(...) \
    _MD_COMPAT_GET_2ND(__VA_ARGS__, _kzalloc_obj_2, _kzalloc_obj_1)(__VA_ARGS__)
#endif

#if !defined(HAVE_KMALLOC_OBJ) && !defined(kmalloc_obj)
#define _kmalloc_obj_1(x)      kmalloc(sizeof(x), GFP_KERNEL)
#define _kmalloc_obj_2(x, gfp) kmalloc(sizeof(x), (gfp))
#define kmalloc_obj(...) \
    _MD_COMPAT_GET_2ND(__VA_ARGS__, _kmalloc_obj_2, _kmalloc_obj_1)(__VA_ARGS__)
#endif

/* kzalloc_objs(type, n) / kzalloc_objs(type, n, gfp) */
#if !defined(HAVE_KZALLOC_OBJS) && !defined(kzalloc_objs)
#define _kzalloc_objs_2(type, n)      kcalloc((n), sizeof(type), GFP_KERNEL)
#define _kzalloc_objs_3(type, n, gfp) kcalloc((n), sizeof(type), (gfp))
#define kzalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kzalloc_objs_3, _kzalloc_objs_2)(__VA_ARGS__)
#endif

#if !defined(HAVE_KMALLOC_OBJS) && !defined(kmalloc_objs)
#define _kmalloc_objs_2(type, n)      kmalloc_array((n), sizeof(type), GFP_KERNEL)
#define _kmalloc_objs_3(type, n, gfp) kmalloc_array((n), sizeof(type), (gfp))
#define kmalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kmalloc_objs_3, _kmalloc_objs_2)(__VA_ARGS__)
#endif

/* kvzalloc_objs / kvmalloc_objs — vmalloc-fallback variants. */
#if !defined(HAVE_KVZALLOC_OBJS) && !defined(kvzalloc_objs)
#define _kvzalloc_objs_2(type, n)      kvzalloc(array_size((n), sizeof(type)), GFP_KERNEL)
#define _kvzalloc_objs_3(type, n, gfp) kvzalloc(array_size((n), sizeof(type)), (gfp))
#define kvzalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kvzalloc_objs_3, _kvzalloc_objs_2)(__VA_ARGS__)
#endif

#if !defined(kvmalloc_objs)
#define _kvmalloc_objs_2(type, n)      kvmalloc(array_size((n), sizeof(type)), GFP_KERNEL)
#define _kvmalloc_objs_3(type, n, gfp) kvmalloc(array_size((n), sizeof(type)), (gfp))
#define kvmalloc_objs(...) \
    _MD_COMPAT_GET_3RD(__VA_ARGS__, _kvmalloc_objs_3, _kvmalloc_objs_2)(__VA_ARGS__)
#endif

/*
 * kmalloc_flex(*ptr, member, count, gfp)
 *
 * Allocates a struct with a trailing flexible-array member. First arg is the
 * dereferenced pointer (so typeof(*ptr) yields the struct type), second is
 * the flex-member name, third is the count, fourth is GFP.
 *
 * Backport via struct_size + kmalloc. struct_size handles the size math
 * (including the flexible-array member) safely against multiplication overflow.
 */
#if !defined(HAVE_KMALLOC_FLEX) && !defined(kmalloc_flex)
#define kmalloc_flex(deref_obj, member, count, gfp) \
    ({ \
        typeof(deref_obj) *_p = NULL; \
        kmalloc(struct_size(_p, member, (count)), (gfp)); \
    })
#endif

#if !defined(HAVE_KZALLOC_FLEX) && !defined(kzalloc_flex)
#define kzalloc_flex(deref_obj, member, count, gfp) \
    ({ \
        typeof(deref_obj) *_p = NULL; \
        kzalloc(struct_size(_p, member, (count)), (gfp)); \
    })
#endif

/*
 * bdev_rot()
 *
 * Upstream renames/adds bdev_rot(b) as the positive form of "is rotational".
 * 6.12 has the negative bdev_nonrot(b). Trivial inverse.
 */
#ifndef HAVE_BDEV_ROT
static inline bool bdev_rot(struct block_device *bdev)
{
    return !bdev_nonrot(bdev);
}
#endif

/*
 * bdev_count_inflight()
 *
 * Upstream adds this helper to count inflight bios on a block_device.
 * 6.12 lacks it. The single user (md.c::is_mddev_idle) compares against
 * the previous count to decide if the device is "idle." Returning 0 makes
 * the device always report idle, which biases the heuristic toward "yes"
 * but is not a correctness issue — sync_speed display may be slightly off.
 *
 * TODO: revisit with a real backport via part_stat_read once we identify
 * the exact field semantics.
 */
#ifndef HAVE_BDEV_COUNT_INFLIGHT
static inline unsigned int bdev_count_inflight(struct block_device *bdev)
{
    (void)bdev;
    return 0;
}
#endif

/*
 * WQ_PERCPU
 *
 * New workqueue flag in upstream. On older kernels, defining it as 0 is
 * a safe no-op — alloc_workqueue ignores unknown bits in the flags arg.
 */
#if !defined(HAVE_WQ_PERCPU) && !defined(WQ_PERCPU)
#define WQ_PERCPU 0
#endif

/*
 * bdev_write_zeroes_unmap_sectors
 *
 * Upstream adds this distinct API to query write-zeroes-with-unmap
 * sector limit, separate from plain bdev_write_zeroes_sectors. Older
 * kernels don't have the distinction.
 *
 * Safe fallback: return 0, which causes md-llbitmap to skip the
 * write-zeroes-unmap optimization and fall back to the standard sync path.
 */
#ifndef HAVE_BDEV_WRITE_ZEROES_UNMAP_SECTORS
static inline unsigned int bdev_write_zeroes_unmap_sectors(struct block_device *bdev)
{
    (void)bdev;
    return 0;
}
#endif

/*
 * timer_container_of(var, callback_timer, fieldname)
 *
 * Upstream renames from_timer() → timer_container_of() (same expansion).
 * Provide the new name as an alias on older kernels.
 */
#if !defined(HAVE_TIMER_CONTAINER_OF) && !defined(timer_container_of)
#define timer_container_of from_timer
#endif

/*
 * bio_init_inline(bio, bdev, nr_vecs, opf)
 *
 * Upstream introduces this variant of bio_init that uses bio->bi_inline_vecs
 * as the bvec array. On older kernels we don't have it; bio_init takes the
 * bvec array explicitly. Pass the inline vecs ourselves.
 */
#ifndef HAVE_BIO_INIT_INLINE
static inline void bio_init_inline(struct bio *bio, struct block_device *bdev,
                                    unsigned short nr_vecs, blk_opf_t opf)
{
    bio_init(bio, bdev, bio->bi_inline_vecs, nr_vecs, opf);
}
#endif

/*
 * bio_submit_split_bioset()
 *
 * Upstream introduces this helper around v6.18 (block/blk-merge.c). Semantics:
 * split off the first `sectors` of `bio` into a new bio using bioset `bs`,
 * chain it, then submit the *remainder* (the original bio, now advanced past
 * `sectors`) via submit_bio_noacct and return the *head* split so the caller
 * keeps processing the front part. On failure the original bio is failed with
 * bio_endio() and NULL is returned.
 *
 * NOTE: the head/remainder direction matters. md callers (raid1/raid10)
 * continue with the returned bio as the head and rely on the helper to
 * resubmit the tail; getting it backwards mislabels the per-bucket barrier
 * sector and clones member I/O for the wrong region. Likewise the error path
 * MUST bio_endio() the bio: callers set R10BIO_Returned on a NULL return,
 * which makes raid_end_bio_io() skip the completion, so the helper owns it.
 *
 * Backport via existing bio_split + bio_chain + submit_bio_noacct, all of
 * which exist on the target kernels (5.14/6.12/6.14/6.17, all < 6.18).
 */
#ifndef HAVE_BIO_SUBMIT_SPLIT_BIOSET
static inline struct bio *bio_submit_split_bioset(struct bio *bio,
                                                   unsigned int sectors,
                                                   struct bio_set *bs)
{
    struct bio *split;

    split = bio_split(bio, sectors, GFP_NOIO, bs);
    if (IS_ERR(split)) {
        bio->bi_status = errno_to_blk_status(PTR_ERR(split));
        bio_endio(bio);
        return NULL;
    }
    bio_chain(split, bio);
    submit_bio_noacct(bio);
    return split;
}
#endif

/*
 * badblocks_check signature change (5.14 → 6.12)
 *
 * Old (RHEL 9 / 5.14): args 3 and 5 are `int sectors` and `int *bad_sectors`.
 * New (6.12+):         args 3 and 5 are `sector_t sectors` and `sector_t *bad_sectors`.
 * Our integrated source uses the new form. Wrap on older kernels.
 */
#ifndef HAVE_BADBLOCKS_CHECK_SECTOR_T_OUTPUTS
#include <linux/badblocks.h>
static inline int ms_badblocks_check_compat(struct badblocks *bb, sector_t s,
                                              sector_t sectors,
                                              sector_t *first_bad,
                                              sector_t *bad_sectors)
{
    int ifirst = 0, isectors = 0;
    int rc;
    rc = badblocks_check(bb, s, (int)sectors, (sector_t *)&ifirst, &isectors);
    if (first_bad) *first_bad = ifirst;
    if (bad_sectors) *bad_sectors = isectors;
    return rc;
}
#define badblocks_check ms_badblocks_check_compat
#endif

/*
 * alloc_page_buffers argument count (5.14 → 6.12)
 *
 * Old: alloc_page_buffers(page, size, bool retry)
 * New: alloc_page_buffers(page, size)
 * Our integrated source calls the 2-arg form.
 */
#ifndef HAVE_ALLOC_PAGE_BUFFERS_2ARG
#include <linux/buffer_head.h>
#define alloc_page_buffers(page, size) alloc_page_buffers((page), (size), false)
#endif

/*
 * UAPI constants removed/added between Ubuntu 24.04 GA (6.8) and 6.12.
 */
#include <linux/raid/md_u.h>
#ifndef LEVEL_LINEAR
#define LEVEL_LINEAR (-1)
#endif

/*
 * REQ_ATOMIC bio flag (atomic-writes infrastructure, ~6.10+).
 * On older kernels atomic-write paths are not exercised; defining as 0
 * makes the bit-OR / test_bit calls no-op without breaking the build.
 */
#include <linux/blk_types.h>
#ifndef REQ_ATOMIC
#define REQ_ATOMIC ((__force blk_opf_t)0)
#endif

/*
 * BLK_FEAT_ATOMIC_WRITES queue_limits feature flag (~6.13+). 6.11 already has
 * struct queue_limits.features and the BLK_FEAT_* enum (so
 * HAVE_QUEUE_LIMITS_FEATURES is set), but this value was added later — that
 * flag is too coarse to gate it. It is an enum value, not a macro, so #ifndef
 * can't see it; gate on the HAVE_ flag that dkms/Makefile.in probes from
 * <linux/blkdev.h>. Defining it to 0 makes `lim.features |= BLK_FEAT_ATOMIC_WRITES`
 * a no-op, mirroring REQ_ATOMIC above (raid1/raid10 don't advertise atomic
 * writes on kernels that lack the flag).
 */
#ifndef HAVE_BLK_FEAT_ATOMIC_WRITES
#define BLK_FEAT_ATOMIC_WRITES 0
#endif

/*
 * BLK_FEAT_PCI_P2PDMA queue_limits feature flag — the gate that lets the array
 * advertise PCI peer-to-peer DMA (GPUDirect Storage) so userspace GUP against
 * /dev/msN is allowed to fetch ZONE_DEVICE P2PDMA (GPU) pages. The flag moved
 * from QUEUE_FLAG_PCI_P2PDMA into queue_limits.features in ~6.11 (Hellwig,
 * "block: move the pci_p2pdma flag to queue_limits"); it is deliberately absent
 * from BLK_FEAT_INHERIT_MASK, so a stacked device must set it explicitly. Like
 * BLK_FEAT_ATOMIC_WRITES it is an enum value, not a macro, so gate on the HAVE_
 * flag dkms/Makefile.in probes from <linux/blkdev.h>. Defining it to 0 makes a
 * stray `lim.features |= BLK_FEAT_PCI_P2PDMA` a no-op on kernels without the
 * feature (e.g. RHEL9/5.14, which also lacks the FOLL_PCI_P2PDMA O_DIRECT path
 * entirely, merged mainline v6.2). The actual P2PDMA code paths are additionally
 * gated on #ifdef HAVE_BLK_FEAT_PCI_P2PDMA — this define only protects a bare OR.
 */
#ifndef HAVE_BLK_FEAT_PCI_P2PDMA
#define BLK_FEAT_PCI_P2PDMA 0
#endif

/*
 * BLK_STS_INVAL (added in 6.10, commit 7ba150834b04).
 *
 * On a kernel that lacks the native BLK_STS_P2PDMA status (the
 * !HAVE_BLK_STS_P2PDMA arm of dkms/patches/0012), an unroutable P2P transfer
 * surfaces as this status on >= 6.17 kernels (BLK_STS_TARGET on <= 6.14).
 * 0012 translates either, on a P2P-tagged completion only, into literal
 * BLK_STS_P2PDMA ahead of raid1/raid10's ordinary completion handling: the
 * range is badblocked, the member is NOT faulted, WantReplacement is NOT
 * set, and the master write succeeds off the surviving leg (upstream's
 * design — a topology property, not a device-health one). Non-P2P INVAL is
 * untouched and keeps upstream's own swallow semantics
 * (raid1_should_handle_error() excludes it since f7b24c7b41f2).
 *
 * Sentinel note: on kernels without HAVE_BLK_FEAT_PCI_P2PDMA the whole
 * P2PDMA surface — including 0012's translation — compiles out entirely
 * (0008's advertise/feature gating) and this 0xFE sentinel is never
 * compared; where BLK_STS_INVAL already exists natively, this #define is
 * inert (guarded directly on the raw macro, not a HAVE_* probe — there is
 * no HAVE_BLK_STS_INVAL flag; it was probed at one point but had no
 * consumer and was dropped from dkms/Makefile.in's feature_flags recipe).
 */
#ifndef BLK_STS_INVAL
#define BLK_STS_INVAL  ((__force blk_status_t)0xFE)
#endif

/*
 * queue_limits transactional update API (added in 6.9, commits c490f226a0eaf
 * and 631d4efb80fb).
 *
 * Newer kernels mutate queue limits via a copy-edit-commit cycle:
 *   lim = queue_limits_start_update(q);
 *   ...mutate lim...
 *   queue_limits_commit_update(q, &lim);   (or _cancel_update on abort)
 * Older kernels just assign q->limits directly.
 *
 * The shims below implement the same contract on 6.8 by copying limits
 * into and out of the queue. There is no transactional rollback, so
 * _cancel_update is a no-op — callers using cancel_update accept that
 * partial mutations to the local `lim` are simply discarded by going
 * out of scope.
 */
#ifndef HAVE_QUEUE_LIMITS_START_UPDATE
static inline struct queue_limits queue_limits_start_update(struct request_queue *q)
{
    return q->limits;
}
#endif

#ifndef HAVE_QUEUE_LIMITS_COMMIT_UPDATE
static inline int queue_limits_commit_update(struct request_queue *q,
                                              struct queue_limits *lim)
{
    q->limits = *lim;
    return 0;
}
#endif

#ifndef HAVE_QUEUE_LIMITS_CANCEL_UPDATE
static inline void queue_limits_cancel_update(struct request_queue *q)
{
    (void)q;
}
#endif

/*
 * queue_limits_set (added in 6.9). One-shot apply of a queue_limits to a
 * queue. On 6.8, also set the queue flags that 6.11+ encodes in
 * lim->features (WRITE_CACHE | FUA | IO_STAT | NOWAIT) — patch 0005
 * elides those bitmap assignments on pre-6.11 kernels, so this shim is
 * the single place where the "features" of an md stacking device get
 * applied to the queue.
 */
#ifndef HAVE_QUEUE_LIMITS_SET
static inline int queue_limits_set(struct request_queue *q,
                                    struct queue_limits *lim)
{
    q->limits = *lim;
    blk_queue_write_cache(q, true, true);
    blk_queue_flag_set(QUEUE_FLAG_IO_STAT, q);
    blk_queue_flag_set(QUEUE_FLAG_NOWAIT, q);
    return 0;
}
#endif

/*
 * queue_limits_stack_bdev (added in 6.9). Stack a block_device's limits
 * onto a queue_limits target. 6.8 has the equivalent at the queue_limits
 * level via blk_stack_limits — same semantics, just no disk-name in
 * mismatch warnings.
 */
#ifndef HAVE_QUEUE_LIMITS_STACK_BDEV
static inline void queue_limits_stack_bdev(struct queue_limits *t,
                                            struct block_device *bdev,
                                            sector_t offset,
                                            const char *name)
{
    blk_stack_limits(t, &bdev_get_queue(bdev)->limits, offset);
    (void)name;
}
#endif

/*
 * queue_limits_stack_integrity_bdev (added in 6.10). Validates and stacks
 * a bdev's blk_integrity profile onto a queue_limits target. Returns true
 * if profiles are compatible, false otherwise.
 *
 * 6.8 has no queue_limits-level integrity stacking — integrity is set up
 * via blk_integrity_register on the gendisk after creation. Returning
 * true here means the caller's "incompatible integrity" rejection path
 * is never taken on 6.8; runtime mismatches still surface elsewhere.
 * This is a deliberate compat trade-off: degraded validation, never a
 * hard build break.
 */
#ifndef HAVE_QUEUE_LIMITS_STACK_INTEGRITY_BDEV
static inline bool queue_limits_stack_integrity_bdev(struct queue_limits *t,
                                                      struct block_device *bdev)
{
    (void)t; (void)bdev;
    return true;
}
#endif

/*
 * bdev_file_open_by_dev / file_bdev (added in 6.9, commit 8acbac46d27dd).
 *
 * The transition replaced struct bdev_handle * with struct file * as the
 * holder type. On 6.8 we reinterpret-cast bdev_handle as struct file *:
 * the pointer is opaque to md.c (only file_bdev() extracts the bdev,
 * and release goes through ms_bdev_file_release() — see below). It is
 * never dereferenced as a real struct file.
 *
 * This works because struct file is forward-declared but its layout is
 * never used on the bdev_file path. Keep this contract intact: any new
 * use of rdev->bdev_file must go through these shims.
 */
#ifndef HAVE_BDEV_FILE_OPEN_BY_DEV
static inline struct file *bdev_file_open_by_dev(dev_t dev, blk_mode_t mode,
                                                   void *holder,
                                                   const struct blk_holder_ops *hops)
{
    return (struct file *)bdev_open_by_dev(dev, mode, holder, hops);
}

static inline struct block_device *file_bdev(struct file *bdev_file)
{
    return ((struct bdev_handle *)bdev_file)->bdev;
}
#endif

/*
 * ms_bdev_file_release(bdev_file)
 *
 * fput() can't be retargeted because md.c also fputs real bitmap files
 * in the same translation unit. Patch 0006 rewrites the two
 * fput(rdev->bdev_file) call sites to use this helper, which dispatches
 * to fput() on 6.9+ and bdev_release() on 6.8.
 */
#ifdef HAVE_BDEV_FILE_OPEN_BY_DEV
static inline void ms_bdev_file_release(struct file *bdev_file)
{
    fput(bdev_file);
}
#else
static inline void ms_bdev_file_release(struct file *bdev_file)
{
    bdev_release((struct bdev_handle *)bdev_file);
}
#endif

/*
 * blk_alloc_disk(lim, node) — 2-arg form added in 6.9 (commit 74fa8f9c5530).
 * On 6.8 the macro is `blk_alloc_disk(node)`. Redefine to accept the
 * (lim, node) signature, dropping `lim` — the limits get applied by a
 * subsequent queue_limits_set() (real on 6.9+ or shim on 6.8).
 *
 * Must come AFTER <linux/blkdev.h> so the original macro is in scope to
 * be #undef'd. The expansion mirrors the 6.8 blkdev.h definition (uses
 * __blk_alloc_disk + a static lock_class_key).
 */
#ifndef HAVE_BLK_ALLOC_DISK_LIM
#ifdef blk_alloc_disk
#undef blk_alloc_disk
#endif
#define blk_alloc_disk(lim, node_id)                                    \
({                                                                       \
    static struct lock_class_key __key;                                  \
    (void)(lim);                                                         \
    __blk_alloc_disk(node_id, &__key);                                   \
})
#endif

/*
 * bh_submit() / bio_endio_bh() — buffer_head bio helpers (upstream ~7.2).
 *
 * Upstream factored the bitmap/metadata buffer_head submit+completion path out
 * of fs/buffer.c into two small helpers: bh_submit() builds a single-page bio
 * from a locked, mapped buffer_head and submits it; bio_endio_bh() recovers the
 * buffer_head from a completed bio and reports success. md-bitmap.c
 * (write_file_page / read_file_page / end_bitmap_write) uses both. The pre-7.2
 * target kernels (RHEL 9/5.14, RHEL 10/6.12, Ubuntu 6.14/6.17) lack them, so
 * port them here. They ship together upstream, so one HAVE_BH_SUBMIT gate
 * (probed from <linux/buffer_head.h> in dkms/Makefile.in) covers both.
 *
 * Judgement calls vs. upstream fs/buffer.c, made for our pre-7.2 targets:
 *  - guard_bio_eod() is DROPPED. It is declared in <linux/bio.h> but is NOT
 *    EXPORT_SYMBOL'd (absent from Module.symvers on 6.12), so an out-of-tree
 *    module cannot link against it. The bitmap buffer_head maps a single
 *    in-file block that never straddles the device's end, so the EOD guard is
 *    a no-op for this path.
 *  - bh->b_page is used (not bh->b_folio): folio accessors may be absent on the
 *    oldest target, while b_page is stable across all four kernels.
 *  - The buffer-flag micro-optimizations are KEPT: test_set_buffer_req,
 *    buffer_write_io_error, clear_buffer_write_io_error, buffer_meta and
 *    buffer_prio are TAS_BUFFER_FNS/BUFFER_FNS-generated and present on every
 *    target (their literal spellings don't appear in the header because the
 *    names are token-pasted by those macros).
 */
#ifndef HAVE_BH_SUBMIT
#include <linux/buffer_head.h>
static inline bool bio_endio_bh(struct bio *bio, struct buffer_head **bhp)
{
    bool success = bio->bi_status == BLK_STS_OK;
    struct buffer_head *bh = bio->bi_private;

    if (unlikely(bio_flagged(bio, BIO_QUIET)))
        set_bit(BH_Quiet, &bh->b_state);
    bio_put(bio);
    *bhp = bh;
    return success;
}

static inline void bh_submit(struct buffer_head *bh, blk_opf_t opf,
                             bio_end_io_t *end_io)
{
    struct bio *bio;

    /* md-bitmap locks+maps the bh (set_buffer_locked/mapped) before calling. */
    if ((opf & REQ_OP_MASK) == REQ_OP_WRITE &&
        test_set_buffer_req(bh) && buffer_write_io_error(bh))
        clear_buffer_write_io_error(bh);
    if (buffer_meta(bh))
        opf |= REQ_META;
    if (buffer_prio(bh))
        opf |= REQ_PRIO;

    bio = bio_alloc(bh->b_bdev, 1, opf, GFP_NOIO);
    bio->bi_iter.bi_sector = (sector_t)bh->b_blocknr * (bh->b_size >> 9);
    /* __bio_add_page() (void, no overflow check) matches upstream __bh_submit:
     * the page is guaranteed to fit the freshly-allocated single-vec bio. The
     * checked bio_add_page() is __must_check on some targets (-Wunused-result),
     * and predating it, __bio_add_page exists wherever the 4-arg bio_alloc()
     * this shim already requires exists. */
    __bio_add_page(bio, bh->b_page, bh->b_size, bh_offset(bh));
    bio->bi_end_io = end_io;
    bio->bi_private = bh;
    /* guard_bio_eod() dropped: not exported to modules; bitmap blocks never
     * straddle EOD. */
    submit_bio(bio);
}
#endif /* HAVE_BH_SUBMIT */

/*
 * BLK_STS_P2PDMA
 *
 * Upstream v6 patch 1 ("block: add BLK_STS_P2PDMA for unsupported
 * peer-to-peer transfers") adds this status. Every kernel we ship to predates
 * it, but v6 patches 7 and 8 reference the constant in ordinary C — without a
 * definition the packaged sources do not compile at all.
 *
 * Value 18 is upstream's, and is unused on every kernel from 6.12 through
 * 7.2-rc5, so it cannot collide with the host block layer, and our patched
 * nvme-rdma and md (which consumes it) agree on the number. The emitter
 * side is a present fact, not a dependency: the sibling meshstor-nvme-rdma
 * package carries upstream v6 p9-p11 ("nvme-rdma: return BLK_STS_P2PDMA for
 * unsupported P2P transfers" and its siblings) and produces status 18 for
 * an unroutable P2P transfer, so md's consumer side is live.
 *
 * DANGER: on a kernel that does not know this status, blk_errors[] has a
 * zero-filled hole at index 18 that still passes the ARRAY_SIZE bounds check,
 * so blk_status_to_errno(18) returns 0 — SUCCESS — for a failed I/O. The value
 * must therefore never escape md. dkms/patches/0012 enforces that with an
 * outbound clamp on the master bio, a tag-gated write-completion dispatch, and
 * a status check after narrow_write_error()'s submit_bio_wait().
 */
#ifndef HAVE_BLK_STS_P2PDMA
#define BLK_STS_P2PDMA ((__force blk_status_t)18)
#endif

/*
 * el10 P2P route fence — see docs (route-fence design, 2026-07-30).
 *
 * Every el10_2 kernel (verified 6.12.0-211.28.1 and the newest
 * 6.12.0-211.40.1) grafts the provider-era p2pdma/DMA core onto old
 * sg-based block/nvme, and the graft maps PCI_P2PDMA_MAP_THRU_HOST_BRIDGE
 * segments to dma_address=0 WITH a success return: the device then DMAs
 * guest/host phys page 0 — silent corruption no status can report.
 * Same-switch BUS_ADDR pairs map correctly.
 *
 * The graft's own signature gates the fence (never a version check):
 * new-era p2pdma (struct p2pdma_provider in pci-p2pdma.h) WITHOUT the
 * new-era block DMA iterator (blk-mq-dma.h). Upstream trees have both or
 * neither.
 *
 * The kernel exports no per-pair classifier (pci_p2pdma_map_type and
 * __pci_p2pdma_update_state are not exported; pci_p2pdma_distance_many
 * collapses BUS_ADDR/THRU_HOST_BRIDGE), so ms proves BUS_ADDR itself,
 * conservatively: misclassification can only FENCE a workable pair
 * (degrading to the ordinary unroutable path), never allow a corrupting
 * one.
 */
/* The last two conditions make this gate a strict subset of 0012's:
 * the fence consumes the R1BIO_P2PDMA/R10BIO_P2PDMA tag, which only
 * exists inside 0012's compat regions. On the el10 line all four
 * conditions hold. */
#if defined(HAVE_P2PDMA_PROVIDER) && !defined(HAVE_BLK_MQ_DMA_H) && \
    defined(HAVE_BLK_FEAT_PCI_P2PDMA) && !defined(HAVE_BLK_STS_P2PDMA)
#define MS_P2P_ROUTE_FENCE_KERNEL 1

#include <linux/pci.h>

/* ACS bits that make the kernel classify a shared-switch pair as
 * THRU_HOST_BRIDGE anyway (TLPs redirected upward). */
#define MS_P2P_ACS_REDIR (PCI_ACS_RR | PCI_ACS_CR | PCI_ACS_UF)

static inline bool ms_p2p_bridge_acs_redirects(struct pci_dev *bridge)
{
	int pos;
	u16 ctrl;

	pos = pci_find_ext_capability(bridge, PCI_EXT_CAP_ID_ACS);
	if (!pos)
		return false;
	pci_read_config_word(bridge, pos + PCI_ACS_CTRL, &ctrl);
	return ctrl & MS_P2P_ACS_REDIR;
}

/* Depth of dev's upstream chain; fills path[] root-first if non-NULL. */
#define MS_P2P_MAX_DEPTH 16
static inline int ms_p2p_upstream_path(struct pci_dev *dev,
				       struct pci_dev **path)
{
	struct pci_dev *chain[MS_P2P_MAX_DEPTH];
	int n = 0, i;

	while (dev && n < MS_P2P_MAX_DEPTH) {
		chain[n++] = dev;
		dev = pci_upstream_bridge(dev);
	}
	if (dev)		/* deeper than MS_P2P_MAX_DEPTH: refuse */
		return -1;
	if (path)
		for (i = 0; i < n; i++)
			path[i] = chain[n - 1 - i];
	return n;
}

/*
 * TRUE only when the provider<->client pair provably maps BUS_ADDR:
 * a common PCIe *switch* ancestor (not the root bus / host bridge), with
 * no ACS redirection on any bridge between either device and it.
 */
static inline bool ms_p2p_pair_is_bus_addr(struct pci_dev *provider,
					   struct pci_dev *client)
{
	struct pci_dev *pa[MS_P2P_MAX_DEPTH], *pb[MS_P2P_MAX_DEPTH];
	int na, nb, common, i;

	if (!provider || !client)
		return false;
	na = ms_p2p_upstream_path(provider, pa);
	nb = ms_p2p_upstream_path(client, pb);
	if (na < 2 || nb < 2)	/* root-bus device: no switch above it */
		return false;

	common = -1;
	for (i = 0; i < na && i < nb; i++) {
		if (pa[i] != pb[i])
			break;
		common = i;
	}
	if (common < 0)
		return false;
	/*
	 * pa[0] is each device's root port (both chains stop at the root
	 * bus, whose devices have no upstream bridge). Sharing only the
	 * root port is not enough: peer TLPs between its subordinates
	 * still route through it, but a shared root PORT alone means the
	 * path crosses no host bridge — however the graft's breakage is
	 * keyed on the kernel's own classification, and upstream
	 * calc_map_type_and_dist() treats any path that reaches a root
	 * port WITHOUT a common switch below it as host-bridge traversal.
	 * So require a common ancestor STRICTLY BELOW the root port: a
	 * downstream/upstream switch port.
	 */
	if (common < 1)
		return false;
	if (pci_pcie_type(pa[common]) != PCI_EXP_TYPE_DOWNSTREAM &&
	    pci_pcie_type(pa[common]) != PCI_EXP_TYPE_UPSTREAM)
		return false;

	/* every bridge above each device, up to and incl. the common
	 * ancestor, must not redirect peer TLPs */
	for (i = common; i < na - 1; i++)
		if (ms_p2p_bridge_acs_redirects(pa[i]))
			return false;
	for (i = common; i < nb - 1; i++)
		if (ms_p2p_bridge_acs_redirects(pb[i]))
			return false;
	return true;
}

/* First PCI ancestor of a block device's disk, or NULL. */
static inline struct pci_dev *ms_p2p_bdev_pci_dev(struct block_device *bdev)
{
	struct device *dev = disk_to_dev(bdev->bd_disk);

	while (dev && !dev_is_pci(dev))
		dev = dev->parent;
	return dev ? to_pci_dev(dev) : NULL;
}

/* PCI device whose BAR contains phys, or NULL. Walks the PCI device
 * list. Returns with a reference held (for_each_pci_dev semantics);
 * the caller drops it once classification is done. */
static inline struct pci_dev *ms_p2p_provider_by_phys(phys_addr_t phys)
{
	struct pci_dev *pdev = NULL;
	int bar;

	for_each_pci_dev(pdev) {
		for (bar = 0; bar < PCI_STD_NUM_BARS; bar++) {
			if (!(pci_resource_flags(pdev, bar) & IORESOURCE_MEM))
				continue;
			if (phys >= pci_resource_start(pdev, bar) &&
			    phys <= pci_resource_end(pdev, bar))
				return pdev;
		}
	}
	return NULL;
}

/*
 * Cached verdict for (provider-page-phys-page, member) pairs. Racy by
 * design: entries are idempotent (the verdict is a pure function of PCI
 * topology), so a lost update only costs a re-classification.
 */
struct ms_p2p_route_ent {
	phys_addr_t prov_base;	/* phys >> 28 covers a BAR comfortably */
	struct pci_dev *member;
	bool ok;
};

static inline bool ms_p2p_route_ok(struct bio *bio,
				   struct block_device *member_bdev)
{
	static struct ms_p2p_route_ent cache[4];
	static unsigned int cache_next;
	phys_addr_t phys, base;
	struct pci_dev *member, *provider;
	unsigned int i, slot;
	bool ok;

	member = ms_p2p_bdev_pci_dev(member_bdev);
	/*
	 * No PCI ancestor: brd (CPU copy, no DMA — safe), loop, or a dm
	 * stack that hides the bottom device. Do NOT fence these — the
	 * member-AND advertise gate already keeps such members from
	 * inviting P2P, and fencing them would break every rig that
	 * builds arrays over brd/dm (this suite included) for a hazard
	 * that only materialises via a DMA-mapping driver. Residual risk,
	 * documented with the other package-pairing hazards: an operator
	 * forcing p2pdma_advertise=always over a dm-STACKED nvme leg on a
	 * graft kernel bypasses this fence.
	 */
	if (!member)
		return true;
	phys = page_to_phys(bio->bi_io_vec[0].bv_page);
	base = phys >> 28;
	for (i = 0; i < ARRAY_SIZE(cache); i++) {
		/* member is the last field written on fill; reading it
		 * first (READ_ONCE) makes a torn entry read as a miss */
		if (READ_ONCE(cache[i].member) == member &&
		    cache[i].prov_base == base)
			return cache[i].ok;
	}
	provider = ms_p2p_provider_by_phys(phys);
	ok = ms_p2p_pair_is_bus_addr(provider, member);
	pci_dev_put(provider);
	slot = cache_next++ & (ARRAY_SIZE(cache) - 1);
	WRITE_ONCE(cache[slot].member, NULL);	/* invalidate before refill */
	cache[slot].prov_base = base;
	cache[slot].ok = ok;
	WRITE_ONCE(cache[slot].member, member);
	return ok;
}
#endif /* HAVE_P2PDMA_PROVIDER && !HAVE_BLK_MQ_DMA_H */

#endif /* MESHSTOR_MD_COMPAT_H */
