#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0
#
# Integration smoke test for Fix A + Fix B together.
#
# Runs the REAL assembly pipeline — bin/build-tarball (`patch -p1`, the
# rename pass, template rendering) — then compiles the result as a kernel
# module against the running kernel.
#
# This proves, end to end, that:
#   * the regenerated patches (Fix B) apply via the production pipeline,
#     not just under the test harness's `patch --fuzz=0`;
#   * patch 0003's `#ifdef HAVE_MDP_SB1_LOGICAL_BLOCK_SIZE` gating (Fix A)
#     survives the rename pass and compiles on the real kernel — if the
#     Makefile.in detector wrongly defined the flag on a kernel lacking the
#     field, `make` would fail with "no member named logical_block_size".
#
# SKIPs (exit 4) when the kernel build tree or toolchain is unavailable.

set -u
# shellcheck source=tools/testing/selftests/dkms/lib.sh
. "$(dirname "$0")/lib.sh"

VER="0.0.0-selftest-smoke"
KDIR="${KDIR:-/lib/modules/$(uname -r)/build}"
OUT="$REPO_ROOT/build/meshstor-ms-$VER"
TARBALL="$REPO_ROOT/build/meshstor-ms-$VER.dkms.tar.gz"

# --- preconditions: missing toolchain/kernel tree/sources is a SKIP -------
command -v make >/dev/null 2>&1 || dkms_skip "make not available"
command -v gcc  >/dev/null 2>&1 || dkms_skip "gcc not available"
[ -d "$KDIR" ]          || dkms_skip "kernel build tree not found: $KDIR"
[ -f "$KDIR/Makefile" ] || dkms_skip "kernel build tree incomplete: $KDIR"
# drivers/md to assemble from: KERNEL_TREE override, in-repo, or a composed
# tree. The harness branch has no drivers/md, so SKIP unless one is available.
KTREE="$(dkms_resolve_kernel_tree)" \
	|| dkms_skip "no drivers/md tree (set KERNEL_TREE= or run bin/rebuild-meshstor-main first)"

smoke_cleanup() { rm -rf "$OUT" "$TARBALL"; }
trap 'smoke_cleanup; dkms_cleanup' EXIT
smoke_cleanup   # clear any stale artifact from a previous run

# --- 1. assemble the DKMS source via the production pipeline ------------
if ! tb_out="$(KERNEL_TREE="$KTREE" KDIR="$KDIR" \
		bash "$REPO_ROOT/bin/build-tarball" "$VER" 2>&1)"; then
	echo "FAIL: bin/build-tarball failed" >&2
	echo "$tb_out" >&2
	exit 1
fi
[ -d "$OUT" ]      || dkms_fail "build-tarball did not produce $OUT"
[ -f "$TARBALL" ]  || dkms_fail "build-tarball did not produce $TARBALL"

# --- 2. Fix A content survived patch apply + rename pass ----------------
# md.c is renamed to ms.c by the rename pass; the HAVE_MDP_* token has no
# md_/MD_ substring so it must pass through untouched.
assert_file_matches "$OUT/ms.c" '#ifdef HAVE_MDP_SB1_LOGICAL_BLOCK_SIZE' \
	"patch 0003's HAVE_MDP_SB1_LOGICAL_BLOCK_SIZE gating must survive into the assembled ms.c"
assert_file_not_matches "$OUT/ms.c" 'LINUX_VERSION_CODE.*KERNEL_VERSION.6, 18' \
	"the old LINUX_VERSION_CODE 6.18 gate must not appear in the assembled ms.c"

# --- 3. the assembled tree compiles as a kernel module ------------------
if ! mk_out="$(make -C "$OUT" KDIR="$KDIR" -j"$(nproc)" 2>&1)"; then
	echo "FAIL: module build failed" >&2
	echo "$mk_out" | tail -40 >&2
	exit 1
fi
for ko in ms_mod.ko raid1_ms.ko raid10_ms.ko; do
	[ -f "$OUT/$ko" ] || dkms_fail "expected module not built: $ko"
done

# --- 4. feature_flags.h was generated at build time ---------------------
ff="$OUT/compat/feature_flags.h"
[ -f "$ff" ] || dkms_fail "feature_flags.h not generated by the build"
assert_file_matches "$ff" 'MESHSTOR_MS_FEATURE_FLAGS_H' \
	"feature_flags.h must be the generated header"

dkms_pass "build-tarball + make: ms_mod/raid1_ms/raid10_ms compile clean from the regenerated patches"
